import {
  Cpu,
  Cable,
  TrafficCone,
  Activity,
} from "lucide-react";

function Hardware() {
  return (
    <div>
      <header>
        <div>
          <p className="eyebrow">
            PHYSICAL PROTOTYPE
          </p>

          <h1>Arduino Hardware Integration</h1>

          <p className="header-description">
            Arduino Uno based miniature traffic signal
            prototype connected to the SmartTrafficAI
            SUMO and TraCI control pipeline.
          </p>
        </div>
      </header>

      <section className="metric-grid">
        <div className="metric-card">
          <div className="metric-icon">
            <Cpu size={22} />
          </div>

          <div>
            <p className="metric-title">
              Controller
            </p>

            <h2>Arduino Uno</h2>

            <span>
              Physical signal controller
            </span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">
            <TrafficCone size={22} />
          </div>

          <div>
            <p className="metric-title">
              Traffic Signal
            </p>

            <h2>3 LEDs</h2>

            <span>
              Red • Yellow • Green
            </span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">
            <Cable size={22} />
          </div>

          <div>
            <p className="metric-title">
              Communication
            </p>

            <h2>USB Serial</h2>

            <span>
              Python ↔ Arduino
            </span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">
            <Activity size={22} />
          </div>

          <div>
            <p className="metric-title">
              Command Pipeline
            </p>

            <h2>SUMO → Arduino</h2>

            <span>
              TraCI + Python bridge
            </span>
          </div>
        </div>
      </section>

      <section className="city-network-card">
        <div className="section-heading">
          <div>
            <p className="eyebrow">
              HARDWARE CONTROL FLOW
            </p>

            <h2>
              SmartTrafficAI Physical Signal Layer
            </h2>

            <p>
              Traffic decisions generated by the SUMO
              simulation are processed through TraCI
              and mapped into serial commands for the
              Arduino traffic signal prototype.
            </p>
          </div>
        </div>

        <div
          style={{
            marginTop: "24px",
            padding: "24px",
            borderRadius: "14px",
            background: "#081722",
            border: "1px solid #1c3d50",
          }}
        >
          <h3 style={{ marginBottom: "20px" }}>
            SUMO → TraCI → Python → Arduino → LEDs
          </h3>

          <div
            style={{
              display: "grid",
              gridTemplateColumns:
                "repeat(auto-fit, minmax(150px, 1fr))",
              gap: "14px",
            }}
          >
            {[
              ["SUMO", "Traffic simulation"],
              ["TraCI", "Signal control"],
              ["Python", "Serial bridge"],
              ["Arduino Uno", "Hardware controller"],
              ["LED Signal", "Physical output"],
            ].map(([title, description]) => (
              <div
                key={title}
                style={{
                  padding: "18px",
                  borderRadius: "12px",
                  border: "1px solid #1c3d50",
                  background: "#0b1d29",
                }}
              >
                <strong>{title}</strong>

                <p
                  style={{
                    marginTop: "6px",
                    color: "#758b9b",
                    fontSize: "13px",
                  }}
                >
                  {description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section
        className="city-network-card"
        style={{
          marginTop: "24px",
        }}
      >
        <div className="section-heading">
          <div>
            <p className="eyebrow">
              EMERGENCY ACTUATION
            </p>

            <h2>
              Ambulance Priority Hardware Logic
            </h2>

            <p>
              The same emergency corridor controller
              used for J1 → J2 → J3 also generates
              physical traffic signal commands.
            </p>
          </div>
        </div>

        <div
          style={{
            marginTop: "24px",
            display: "grid",
            gap: "12px",
          }}
        >
          <div
            style={{
              padding: "16px 20px",
              borderRadius: "12px",
              background: "#081722",
              border: "1px solid #1c3d50",
            }}
          >
            <strong>AMB_001 detected</strong>

            <p
              style={{
                color: "#758b9b",
                marginTop: "5px",
              }}
            >
              Emergency green corridor activated.
            </p>
          </div>

          <div
            style={{
              padding: "16px 20px",
              borderRadius: "12px",
              background: "#081722",
              border: "1px solid #1c3d50",
            }}
          >
            <strong>
              J1 → J2 → J3
            </strong>

            <p
              style={{
                color: "#758b9b",
                marginTop: "5px",
              }}
            >
              EMERGENCY_GREEN command generated
              sequentially for corridor priority.
            </p>
          </div>

          <div
            style={{
              padding: "16px 20px",
              borderRadius: "12px",
              background: "#081722",
              border: "1px solid #1c3d50",
            }}
          >
            <strong>
              Ambulance cleared corridor
            </strong>

            <p
              style={{
                color: "#758b9b",
                marginTop: "5px",
              }}
            >
              Normal traffic signal state restored.
            </p>
          </div>
        </div>
      </section>

      <section
        className="city-network-card"
        style={{
          marginTop: "24px",
        }}
      >
        <div className="section-heading">
          <div>
            <p className="eyebrow">
              IMPLEMENTATION STATUS
            </p>

            <h2>Hardware Prototype Status</h2>
          </div>
        </div>

        <div
          style={{
            marginTop: "20px",
            lineHeight: "1.9",
            color: "#8ca0ae",
          }}
        >
          <p>
            ✓ Arduino Uno traffic signal firmware implemented
          </p>

          <p>
            ✓ Python serial communication bridge implemented
          </p>

          <p>
            ✓ SUMO / TraCI emergency controller connected to
            hardware command layer
          </p>

          <p>
            ✓ J1 → J2 → J3 emergency command mapping validated
            through the integrated controller
          </p>

          <p>
            ◉ Physical Arduino traffic-light circuit assembled
          </p>

          <p>
            ◉ Final USB serial hardware validation pending
          </p>
        </div>
      </section>
    </div>
  );
}

export default Hardware;